#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["dealcontext-client @ git+https://github.com/pocketcontext/dealcontext.git@bf5ceae81aed7378fcffe3581a7dedafe9e8b176"]
# ///
from dealcontext_client.cli import main

if __name__ == "__main__":
    raise SystemExit(main())
